version: '3.3'

services:
  php:
    container_name: mailing-php
    hostname: mailing-php
    build:
      context: ./
      dockerfile: docker/Dockerfile
    links:
      - mysql:mysql
    ports:
      - "80:9001"
    environment:
      - MYSQL_DATABASE=mailing
      - MYSQL_HOST=mailing-mysql
      - MYSQL_USER=mailing
      - MYSQL_PASSWORD=mailing
      - USER_RANDOM_MAX=1000000
      - USER_SAMPLE_DATA=true
    volumes:
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/log/php:/var/log/php
      - ./docker/log/supervisord:/var/log/supervisord
      - ./:/var/www/mailing
    depends_on:
      - mysql
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    restart: always

  mysql:
    container_name: mailing-mysql
    hostname: mailing-mysql
    image: mysql:latest
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/log/mysql:/var/log/mysql
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d/
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mailing
      - MYSQL_USER=mailing
      - MYSQL_PASSWORD=mailing
    restart: always
